# Generated by Django 5.2.6 on 2025-11-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidad',
            name='icono_url',
            field=models.URLField(blank=True, help_text='URL del icono de la habilidad', null=True),
        ),
    ]
