# Generated by Django 5.2.6 on 2025-11-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_habilidad_icono_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidad',
            name='tipo',
            field=models.CharField(choices=[('tecnica', 'Técnica'), ('blanda', 'Blanda')], default='tecnica', max_length=10),
        ),
    ]
