# Generated by Django 5.2.6 on 2025-11-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_habilidad_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidad',
            name='icono_url',
            field=models.URLField(blank=True, help_text='URL del icono de la habilidad (ej: Font Awesome, Bootstrap Icons)', null=True),
        ),
    ]
